### ISSUE TITLE
Get app version from env

### ISSUE THREAD

**Issue by amonsosanz** [hermeznetwork/bridge-ui#24]
Currently, we are showing `Hermez Polygon Bridge v.01` on the Settings page:

![image](https://user-images.githubusercontent.com/15896177/160886890-3ade4409-4f4f-48ce-80c2-f2ffa4bf5d0b.png)

We should change this to `Polygon Hermez Bridge` and get the version of the app from the `package.json`:

```
REACT_APP_VERSION=$npm_package_version
```

**Comment by elias-garcia** [comment]
Closing as it was implemented in #76

**Comment by elias-garcia** [comment]
Closing as it was implemented in #76
