### ISSUE TITLE
Sync MetaMask network with the chain in the form

### ISSUE THREAD

**Issue by elias-garcia** [hermeznetwork/bridge-ui#70]
When we change the network directly in MetaMask we need to sync the chains `from` and `to` used in the form in the `Home` page to match the new selected network.

**Comment by amonsosanz** [comment]
To keep consistency between the UI and MetaMask, we should also consider doing it the other way around, i.e, when the user selects a network in the `from` input in Home, we should request MetaMask to switch the network.
